removed old RH commented code. checked SPAWN_SOCKET option

diff --git a/etc/init.d/fcgi b/etc/init.d/fcgi
--- a/etc/init.d/fcgi
+++ b/etc/init.d/fcgi
@@ -1,24 +1,13 @@
 #!/bin/sh
 #
-# nginx-fcgi
+# fcgi
 #
 # chkconfig:	345 85 15
-# description:	nginx-fcgi is a perl script to provide simple cgi support for nginx http daemon
-# processname:	nginx-fcgi
-# pidfile:	/var/run/nginx-fcgi.pid
-# config:	/etc/sysconfig/nginx-fcgi
+# description:	fcgi is a perl script to provide simple cgi support
+# processname:	fcgi
 
-
-# Source function library
-#. /etc/rc.d/init.d/functions
-
-# Get network config
-#. /etc/sysconfig/network
-
-# Get service config
 ME=`basename $0`
 
-PROG=/var/www/mason/mason_fcgi.pl
 CONFIG=/etc/default/$ME
 if [ ! -f $CONFIG ]; then
 	echo >&2 "fcgi: Missing $CONFIG config file"
@@ -31,28 +20,22 @@ fi
 checkconfig() {
 
 	if [ -z "$SPAWN_UID" ]; then
-		echo >&2 "fcgi: Missing SPAWN_UID value (user name)"
+		echo >&2 "$ME: Missing SPAWN_UID value (user name) in $CONFIG"
 		exit 1
 	fi
 
 	if [ -z $SPAWN_GID ]; then
-		echo >&2 "fcgi: Missing SPAWN_GID value (group name)"
+		echo >&2 "$ME: Missing SPAWN_GID value (group name) in $CONFIG"
 		exit 1
-	fi
-
-	if [ -n "$SPAWN_PORT" -a -n "$SPAWN_SOCKET" ]; then
-		echo >&2 "fcgi: port and socket can not be used simulatenously"
-		exit 1
-	fi
-
-	if [ -n "$SPAWN_ADDR" -a -z "$SPAWN_PORT" ]; then
-		 echo >&2 "fcgi: bind address specified but no port"
-		 exit 1
 	fi
 
 	if [ -z "$SPAWN_LOG" ]; then
-		echo >&2 "fcgi: missing declaration of log file"
+		echo >&2 "$ME: missing declaration of log file SPAWN_LOG in $CONFIG"
 		exit 1
+	fi
+
+	if [ -z "$SPAWN_SOCKET" ]; then
+		echo 2>&2 "$ME: missing SPAWN_SOCKET in $CONFIG
 	fi
 
 	USER_ID=`id -u $SPAWN_UID 2>&1 > /dev/null`
@@ -62,14 +45,6 @@ checkconfig() {
 		echo >&2 "fcgi: $SPAWN_UID user not found in system"
 		exit 1
 	fi
-
-#	USER_GID=`getgid $SPAWN_GID 2>&1 > /dev/null`
-#	if [ -z "$USER_GID" ]; then
-#		USER_GID=`getgid $SPAWN_GID`
-#	else
-#		echo >&2 "nginx-fcgi: $SPAWN_UID group not found in system"
-#		exit 1;
-#	fi
 }
 
 start() {
@@ -77,7 +52,7 @@ start() {
 	if [ ! -f /var/lock/subsys/$ME ]; then
 		echo -n $ME: 
 		
-		start-stop-daemon --start --exec $PROG --group $SPAWN_GID --chuid $SPAWN_UID -- --pid $SPAWN_PID "$SPAWN_OPT" --socket $SPAWN_SOCKET --log $SPAWN_LOG
+		start-stop-daemon --start --exec $FCGI_SCRIPT --group $SPAWN_GID --chuid $SPAWN_UID -- --pid $SPAWN_PID "$SPAWN_OPT" --socket $SPAWN_SOCKET --log $SPAWN_LOG
 		RETVAL=$?
 		if [ $RETVAL -eq 0 ]; then
 			echo started
